import pygame


#image:
card_back = pygame.image.load("image/special_R/card_back_resize.png")

card_empty = pygame.image.load("image/special_R/card_emptyR.png")
#cards
c_Clover =  pygame.image.load("image/special_R/card_cloverR.png")
cA_Clover = pygame.image.load("image/Card_resize/Clover/A_Clover.png")
c2_Clover = pygame.image.load("image/Card_resize/Clover/2_Clover.png")
c3_Clover = pygame.image.load("image/Card_resize/Clover/3_Clover.png")
c4_Clover = pygame.image.load("image/Card_resize/Clover/4_Clover.png")
c5_Clover = pygame.image.load("image/Card_resize/Clover/5_Clover.png")
c6_Clover = pygame.image.load("image/Card_resize/Clover/6_Clover.png") 
c7_Clover = pygame.image.load("image/Card_resize/Clover/7_Clover.png")
c8_Clover = pygame.image.load("image/Card_resize/Clover/8_Clover.png")
c9_Clover = pygame.image.load("image/Card_resize/Clover/9_Clover.png")
c10_Clover = pygame.image.load("image/Card_resize/Clover/10_Clover.png")
cJ_Clover = pygame.image.load("image/Card_resize/Clover/J_Clover.png")
cQ_Clover = pygame.image.load("image/Card_resize/Clover/Q_Clover.png")
cK_Clover = pygame.image.load("image/Card_resize/Clover/K_Clover.png")

c_Heart =  pygame.image.load("image/special_R/card_heartR.png")
cA_Heart = pygame.image.load("image/Card_resize/Heart/A_Heart.png")
c2_Heart = pygame.image.load("image/Card_resize/Heart/2_Heart.png")
c3_Heart = pygame.image.load("image/Card_resize/Heart/3_Heart.png")
c4_Heart = pygame.image.load("image/Card_resize/Heart/4_Heart.png")
c5_Heart = pygame.image.load("image/Card_resize/Heart/5_Heart.png")
c6_Heart = pygame.image.load("image/Card_resize/Heart/6_Heart.png")
c7_Heart = pygame.image.load("image/Card_resize/Heart/7_Heart.png")
c8_Heart = pygame.image.load("image/Card_resize/Heart/8_Heart.png")
c9_Heart = pygame.image.load("image/Card_resize/Heart/9_Heart.png")
c10_Heart = pygame.image.load("image/Card_resize/Heart/10_Heart.png")
cJ_Heart = pygame.image.load("image/Card_resize/Heart/J_Heart.png")
cQ_Heart = pygame.image.load("image/Card_resize/Heart/Q_Heart.png")
cK_Heart = pygame.image.load("image/Card_resize/Heart/K_Heart.png")

c_Diamond =  pygame.image.load("image/special_R/card_diamondR.png")
cA_Diamond = pygame.image.load("image/Card_resize/Diamond/A_Diamond.png")
c2_Diamond = pygame.image.load("image/Card_resize/Diamond/2_Diamond.png")
c3_Diamond = pygame.image.load("image/Card_resize/Diamond/3_Diamond.png")
c4_Diamond = pygame.image.load("image/Card_resize/Diamond/4_Diamond.png")
c5_Diamond = pygame.image.load("image/Card_resize/Diamond/5_Diamond.png")
c6_Diamond = pygame.image.load("image/Card_resize/Diamond/6_Diamond.png")
c7_Diamond = pygame.image.load("image/Card_resize/Diamond/7_Diamond.png")
c8_Diamond = pygame.image.load("image/Card_resize/Diamond/8_Diamond.png")
c9_Diamond = pygame.image.load("image/Card_resize/Diamond/9_Diamond.png")
c10_Diamond = pygame.image.load("image/Card_resize/Diamond/10_Diamond.png")
cJ_Diamond = pygame.image.load("image/Card_resize/Diamond/J_Diamond.png")
cQ_Diamond = pygame.image.load("image/Card_resize/Diamond/Q_Diamond.png")
cK_Diamond = pygame.image.load("image/Card_resize/Diamond/K_Diamond.png")

c_Pica =  pygame.image.load("image/special_R/card_picaR.png")
cA_Pica = pygame.image.load("image/Card_resize/Pica/A_Pica.png")
c2_Pica = pygame.image.load("image/Card_resize/Pica/2_Pica.png")
c3_Pica = pygame.image.load("image/Card_resize/Pica/3_Pica.png")
c4_Pica = pygame.image.load("image/Card_resize/Pica/4_Pica.png")
c5_Pica = pygame.image.load("image/Card_resize/Pica/5_Pica.png")
c6_Pica = pygame.image.load("image/Card_resize/Pica/6_Pica.png")
c7_Pica = pygame.image.load("image/Card_resize/Pica/7_Pica.png")
c8_Pica = pygame.image.load("image/Card_resize/Pica/8_Pica.png")
c9_Pica = pygame.image.load("image/Card_resize/Pica/9_Pica.png")
c10_Pica = pygame.image.load("image/Card_resize/Pica/10_Pica.png")
cJ_Pica = pygame.image.load("image/Card_resize/Pica/J_Pica.png")
cQ_Pica = pygame.image.load("image/Card_resize/Pica/Q_Pica.png")
cK_Pica = pygame.image.load("image/Card_resize/Pica/K_Pica.png")

#letters
letter_a = pygame.image.load("image/letter/a.png")
letter_b = pygame.image.load("image/letter/b.png")
letter_c = pygame.image.load("image/letter/c.png")
letter_d = pygame.image.load("image/letter/d.png")
letter_e = pygame.image.load("image/letter/e.png")
letter_f = pygame.image.load("image/letter/f.png")
letter_g = pygame.image.load("image/letter/g.png")
letter_h = pygame.image.load("image/letter/h.png")
letter_i = pygame.image.load("image/letter/i.png")
letter_j = pygame.image.load("image/letter/j.png")
letter_k = pygame.image.load("image/letter/k.png")
letter_l = pygame.image.load("image/letter/l.png")
letter_m = pygame.image.load("image/letter/m.png")
letter_n = pygame.image.load("image/letter/n.png")
letter_o = pygame.image.load("image/letter/o.png")
letter_p = pygame.image.load("image/letter/p.png")
letter_q = pygame.image.load("image/letter/q.png")
letter_r = pygame.image.load("image/letter/r.png")
letter_s = pygame.image.load("image/letter/s.png")
letter_t = pygame.image.load("image/letter/t.png")
letter_u = pygame.image.load("image/letter/u.png")

# letter_v = pygame.image.load("image/letter/f.png")
# letter_w = pygame.image.load("image/letter/g.png")
# letter_x = pygame.image.load("image/letter/h.png")
# letter_y = pygame.image.load("image/letter/i.png")
# letter_z = pygame.image.load("image/letter/j.png")


#numbI_one = pygame.image.load("numbers/numb/one_32.png")